# Build stage
FROM golang:1.23-alpine AS builder
#
# Set working directory
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

COPY docs ./docs
COPY .env.dev .env.dev

# Build with memory optimization flags
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o main .

# Final stage
FROM alpine:latest

# Set working directory
WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/main .
COPY --from=builder /app/.env.dev .env.dev
COPY --from=builder /app/package.json .

# Copy .env.dev if it exists, otherwise skip


# Set default environment
# ARG ENV=prod

# Set environment variables
ENV PORT=5000
ENV GOGC=50
ENV GOMEMLIMIT=384MiB
ENV GOMAXPROCS=2

# Expose port
EXPOSE 5000

# Run with memory limits
# Use environment variable to set the environment flag
# Default to development (-d) for dev image
CMD ./main dev