name: Build and Push Dockerfile.dev

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: lovee12345e
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image from Dockerfile.dev
        run: |
          docker build -f Dockerfile.dev -t lovee12345e/reports-api:dev .

      - name: Push Docker image
        run: |
          docker push lovee12345e/reports-api:dev
